kubereboot/kured

- pkg/notifications/slack/slack.go
Otherwise it panics for nil body
> Close body after error check

- cmd/kured/main.go
- pkg/notifications/slack/slack.go
> Notify slack before draining a node

- kured-ds.yaml
> Tolerate master node-role NoSchedule taint

- README.md
> Document embedded kubectl/client-go versions

- README.md
- cmd/kured/main.go
- kured-ds.yaml
- pkg/notifications/slack/slack.go
> Added slack channel name configuration

- cmd/kured/Dockerfile
Currently Kured is being reported with having security vulnerabilities by our CSP because of the base image.
> Upgrading to latest alpine

- DEVELOPMENT.md
- README.md
- kured-ds.yaml
Also point out how to create the dockerhub.yaml file, update other release related instructions.
closes: #97
> Prepare 1.3.0 release

- README.md
I setup #kured on Slack to make coordination a bit easier.
> point to kured Slack

- .circleci/config.yml
Needed for #140.
Docs: https://circleci.com/docs/2.0/configuration-reference/#filters
/cc @ckotzbauer
> make sure Circle CI ignores the 'gh-pages' branch

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/values.yaml
> prepare chart-release for 1.4.1

- .github/workflows/chart-release.yml
- README.md
- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/values.yaml
https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret
> Use GitHub token

- README.md
I used https://github.com/fluxcd/charts/blob/gh-pages/index.md as inspiration - thanks Stefan!
> add README explaining how to install kured from chart

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/templates/daemonset.yaml
- charts/kured/templates/servicemonitor.yaml
- charts/kured/values.yaml
- fixed servicemonitor indent
- fixed quotes for arguments
- bumped to upcoming kured 1.4.3
Fixes: #161 
Ref: #140
> Several small chart fixes

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/templates/_helpers.tpl
- charts/kured/templates/daemonset.yaml
- charts/kured/templates/service.yaml
- charts/kured/templates/servicemonitor.yaml
- charts/kured/values.yaml
- Restructured service definition
- added "matchLabels" template
#140
> Additional chart changes for service-handling

- DEVELOPMENT.md
- README.md
- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/values.yaml
Also drop bit in the docs about updating image tag - not necessary if you use the instructions.
> Prep for 1.4.4 release

- README.md
Look up last release on Github, then use it for installation.
> update install instructions to use latest

- DEVELOPMENT.md
- README.md
- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/values.yaml
- update chart versions
- update release documentation
- Christian and David are the chart maintainers
> Prepare 1.5.0 release

- cmd/kured/main.go
- pkg/daemonsetlock/daemonsetlock.go
This is a follow-up on #54, #119 & #143
- I renamed the --annotationTTL flag into --lockTTL as I believe it is a more pertinent nomenclature
- I fixed its implementation as reported not being functional in #143
> Replaced --annotationTTL with --lockTTL and made it work correctly

- pkg/daemonsetlock/daemonsetlock.go
- pkg/delaytick/delaytick.go
- pkg/notifications/slack/slack.go
- pkg/timewindow/days.go
Without this patch, lint will complain about a few cosmetic details.
> Make go lint on pkg folder happier

- .github/workflows/go-lint.yaml
This should be merged after the first lint fixes ( #215 and #222 ).
Those two PR have been included in this one, but I intend to rebase to have only this one in this PR.
> Add Lint job in github actions

- .github/kind-cluster-1.17.yaml
- .github/kind-cluster-1.18.yaml
- .github/kind-cluster-1.19.yaml
- .github/workflows/smoke-tests.yml
This increases the test matrix for the kind smoke tests.
> Increase test matrix for smoke tests

- tests/kind/follow-coordinated-reboot.sh
When a failure is happening and the cluster doesn't manage to
be back up on time, we exit 1, and don't show docker logs.
This is a problem, as we would benefit from a detailed docker
output on those cases, when debugging.
This fixes it by ensuring the logging is always done at the
exit of the script.
> Improve coordinated reboot output

- .github/workflows/shellcheck.yml
> Add Shellcheck

- charts/kured/Chart.yaml
- charts/kured/values.yaml
Bumping the helm chart with minor version bump, due to minor
version bump of the kured appVersion.
> Update helm chart

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/templates/daemonset.yaml
- charts/kured/values.yaml
Adds configuration of additional pod labels, like cost center.
> add podLabels parameter

- .github/workflows/periodics-daily.yaml
> Extend close-duration for stale issues and prs

- Makefile
- charts/kured/Chart.yaml
- charts/kured/templates/daemonset.yaml
- charts/kured/values.yaml
- Remove `sed` command for `values.yaml` in Makefile.
- Set tag in `values.yaml` to empty string
> Use chart appVersion as default image-tag

- .github/workflows/on-main-push-charts.yaml
- .github/workflows/on-main-push.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
- .github/workflows/periodics-daily.yaml
- README.md
- charts/kured/Chart.yaml
Also make markdownlint happier in a couple of places.
Please only merge after all other steps of #252 are resolved.
Eventually closes: #252
> Change default branch to 'main'.

- .github/workflows/on-pr-charts.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/periodics-daily.yaml
- DEVELOPMENT.md
- Makefile
Without this, we get multiple questions about our testing.
This should help clarify the tests and our coverage by:
- Simplifying our coverage
- Documenting better the purpose of each workflow file
- Documenting our testing and development activities better.
> Clarify and simplify tests

- go.mod
- go.sum
> update golang.org/x/crypto - break out of #349

- .github/kind-cluster-1.19.yaml
- .github/kind-cluster-1.20.yaml
- .github/kind-cluster-1.21.yaml
- .github/workflows/on-pr-charts.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/periodics-daily.yaml
> Update test matrix to latest 3 sets of k8s releases

- cmd/kured/main.go
> fix slack deprecation notice

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/templates/daemonset.yaml
- charts/kured/values.yaml
Hi all,
This PR adds `--reboot-command` flag in the chart.
Let me know if anything needs to be changed.
> Added rebootCommand values

- cmd/kured/Dockerfile
> build: updated to alpine@3.14

- .github/dependabot.yml
> update docker images too

- .github/dependabot.yml
> follow up to #465

- .github/workflows/on-main-push.yaml
- .github/workflows/on-tag.yaml
- Makefile
> Add ghcr.io as second registry

- .github/workflows/on-main-push.yaml
- .github/workflows/on-tag.yaml
cf https://github.com/weaveworks/kured/runs/4355900686?check_suite_focus=true
> fix ghcr.io login

- charts/kured/Chart.yaml
- charts/kured/README.md
- kured-ds.yaml
Update chart post 1.8.2 release
> update image tag to 1.8.2

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/templates/daemonset.yaml
- charts/kured/values.minikube.yaml
- charts/kured/values.yaml
This PR adds the chart setup for log-format support as defined in #455 .
> Jsonlogging chart

- cmd/kured/main.go
as suggested in https://github.com/weaveworks/kured/pull/464#discussion_r759873928 proposing this small fix in a separate PR
> small fix in deprecation log messages

- README.md
Update Teams webhook
Update Shouttr documentation version to v0.5
> Teams webhook documentation

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/templates/daemonset.yaml
- charts/kured/values.yaml
> adding value containerSecurityContext to helm chart #521

- charts/kured/Chart.yaml
- charts/kured/templates/daemonset.yaml
> helm: fix tolerations on 1.24

- .github/workflows/on-main-push.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
- .github/workflows/periodics-daily.yaml
Follow up from #548, let's try doing the string concatenation inside quotes
> ci: substring suffix inside quotes

- CODE_OF_CONDUCT.md
- README.md
GitHub will pick this up in the "community standards" section now as well.
> add CoC file

- charts/kured/Chart.yaml
- charts/kured/README.md
- charts/kured/templates/_helpers.tpl
https://helm.sh/docs/chart_best_practices/labels/#standard-labels
Suggesting this as a fix for #604
> Switch to standard labels from Helm best practices

- charts/kured/Chart.yaml
- charts/kured/README.md
- kured-ds.yaml
Signed-off-by: Christian Kotzbauer <git@ckotzbauer.de>
> Prepare release 1.10.2

- MAINTAINERS
- README.md
- Also sort maintainers alphabetically.
- Make markdownlint happy.
> Update Slack information - point to CNCF Slack.

- README.md
This adds clarity to avoid temporary issues related to the
migration.
> Add a warning to inform users about move

- DCO
- DEVELOPMENT.md
> require DCO from now on

- .github/workflows/on-main-push.yaml
- .github/workflows/on-tag.yaml
This should be one credential less to manage.
> Use github token instead of bot accounts

- .github/workflows/on-main-push.yaml
- .github/workflows/on-tag.yaml
Signed-off-by: Christian Kotzbauer <git@ckotzbauer.de>
> fix: fix spdx-sbom-handling

- .github/workflows/codeql.yml
> add CodeQL scan job

- README.md
Remove warning about repo move.
> Add ArtifactHub badge

- .clomonitor.yml
Apparently https://github.com/kubereboot/website/pull/18 was not the right place for the file.
> website: we don't use analytics

- .github/workflows/on-main-push.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
- .github/workflows/periodics-daily.yaml
> simplify the setup of go in workflows

- DEVELOPMENT.md
> adjust link to CONTRIBUTING file

- .github/dependabot.yml
> Fix location of Dockerfile for dependabot

- README.md
> add mailing list

- CONTRIBUTING.md
- kured-ds.yaml
> prepare for 1.12.1 release

- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
- .github/workflows/periodics-daily.yaml
> Move to aquasecurity/trivy-action instead

- go.mod
update Go to 1.19, it's used in k8s 1.24 as well
> update Go to 1.19

- go.mod
- go.sum
> Drop the golang.org/x/text replacement

- kured-ds.yaml
This PR fixes the missing ports config in the DaemonSet Yaml file. Closes #741
> Add ports config to DaemonSet yaml. Closes #741

- MAINTAINERS
> doc: Updated maintainers file

- CONTRIBUTING.md
- Explain kured code structure
- Update links, as some docs have moved
- Readability and fix typos
> Update contributor docs

- .github/workflows/on-main-push.yaml
- .github/workflows/on-tag.yaml
- .gitignore
We moved to hack/bin in commit
608abc6e89093f344979e70ecf5bea5e52e8758e.
> Remove all mentions of .tmp

- CONTRIBUTING.md
Without this, ppl might be wondering how to use e2e test, especially on slower machines.
> Clarify features for e2e test

- cmd/kured/main.go
Do not merge until #1015  is merged.
There is no need to continuously reallocate the check blockers.
They only need to be defined once.
> Cleanup blockCheckers

- kured-ds-signal.yaml
- kured-ds.yaml
Signed-off-by: Jean-Philippe Evrard <open-source@a.spamming.party>
> chore: update release

- MAINTAINERS
I took inspiration from the Flux `MAINTAINERS` file.
> dholbach steps down

- CONTRIBUTING.md
Also include a thank you note to JetBrains for their awesome IDE.
> Clarify contributing docs
