kubereboot/kured

kured-ds.yaml

Due to 
metadata:
name: kured            # Must match `--ds-name`
namespace: kube-system # Must match `--ds-namespace`
There should be 
- --ds-name=kured
- --ds-namespace=kube-system
As args.

Looks like typo in daemonset

---

README.md

As `kured` was brought up as an example in the conversation, I thought I'd add some info on how to get in touch at the bottom of the `README.md` file.
If you're happy with that, I'm happy to update the other README files for the other repos too.
One bit I wasn't sure about was the IRC suggestion (I stole it from https://www.weave.works/help/), AFAIUI the Slack/IRC bridge service will be terminated soon (https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP).

add information on how to get in touch at the bottom of the page

---

README.md
kured-ds.yaml
kured-rbac.yaml

- Added kured service account
- Added kured clusterrole
- Added kured clusterrolebinding
- Updated README.md documentation to include deploying with RBAC support
Thanks to @phsiao and @liggitt who helped point me in the right direction on getting the correct rules for getting the drain working.
I changed the url for the `kubectl apply -f` commands to just point to master as they referenced a release previously which will make maintaining an example deployment easier.  The existing manifests don't specify the image label so if someone were to run the kubectl apply command pointed at the tag/release they would get the latest image and not the version of the binary associated with the tag/release anyhow.  Also with the addition of the `serviceaccount` the manifest in the release won't work …

Update provided manifests to support a service account and RBAC

---

.circleci/config.yml

So that creating a GitHub release triggers an appropriately versioned build.

Enable CI builds on tags

---

cmd/kured/Dockerfile
cmd/kured/main.go
kured-ds.yaml

Use the tools installed in the host to effect reboots, eventually facilitating the use of commands such as `needs-restart` to determine if reboots are required.

Enter host mount namespace

---

README.md
kured-ds.yaml

* Add FAQ around lack of `latest` tag on quay
* Bump manifest version in example
* Rework for host mount namespace change

Update docs for 1.1.0 release

---

README.md
cmd/kured/main.go
kured-ds.yaml

This PR adds functionality to block individual nodes from rebooting in the presence of specific pods, as determined by a label selector:
```
--blocking-pod-selector=runtime=long,cost=expensive
```
see documentation in the commit for more details.

Allow selected pods to prevent reboots

---

Makefile

Shouldn't need this as the CI does `dep ensure` before building.

Remove spurious `go get` from Makefile

---

README.md
cmd/kured/Dockerfile
cmd/kured/main.go
kured-ds.yaml
pkg/timewindow/days.go
pkg/timewindow/days_test.go
pkg/timewindow/timewindow.go
pkg/timewindow/timewindow_test.go

Similar to #20 but allows us to specify, e.g., business hours so we don't get awoken in the middle of the night :-).

Reboot only within time window specified on commandline

---

DEVELOPMENT.md
README.md

add some notes, particularly on testing/creating new releases

add development docs

---

cmd/kured/Dockerfile

Updating alpine to the latest version.
Tested this version of alpine and running fine, keeping versions of dependencies up to date.

Keeping alpine fresh

---

.circleci/config.yml
go.mod

New Go image is recommended in https://circleci.com/docs/2.0/circleci-images/
fixes: #129

Update Go version to 1.13

---

cmd/kured/Dockerfile

The upside is that image building will always use the latest
stable version of the alpine OS, which might include security fixes.
The downside is that it's less reproducible, because the full
version isn't given.
While this commit isn't necessary per se, it's nice to have
an image that will be up to date, when we'll build it.

Unpin base docker image

---

cmd/kured/main.go

Before commanding a reboot, it would be good if the node id is printed.
In the cloud, this could be taken by any centralized monitoring tool, and trigger some actions.
For example: On Azure, Azure Monitor could get this log, send notifications
Another use case is being able to query this together with applications logs when troubleshooting

print the node id when commanding a reboot

---

README.md
cmd/kured/main.go
pkg/daemonsetlock/daemonsetlock.go
pkg/daemonsetlock/daemonsetlock_test.go

I have observed this behavior when running kured together with cluster autoscaler, reason why this idea was born.
- CA adds nodes (CoreOS in my case)
- Nodes are starting to reboot themselves after fetching updates, ie. annotation has been added (lock owned by node 123.123.123.123)
- CA decides to downscale ASG (not all nodes had a chance to reboot yet), and it decides to cut off node 123.123.123.123
- Need to manually take off annotation
This PR introduces `--annotationTTL` parameter, by default set to 0 (means do not use this feature), which allows other kured pods to take off the lock if it has expired.
Comparing kured to [coreos-update-operator](https://github.com/coreos/container-linux-update-operator) latter one is adding lock annotation onto node object which makes such feature as …

Adding --annotation-ttl for automatic unlock

---

.circleci/config.yml

Follow the lead of https://github.com/weaveworks/flagger/blob/gh-pages/.circleci/config.yml

Don't run Circle CI on gh-pages branch

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.yaml

See issue #167
It seems to me that extraArgs does not support my use-case. 
Support setting extraEnvs so that extraArgs can refer to env variables such as $slackHookUrl

Chart: Support extraEnvVars

---

charts/kured/Chart.yaml
charts/kured/templates/daemonset.yaml

The Helm chart config option alertFilterRegexp does not work with quotes in the most recent version 2.0.3.
When using
```
configuration:
alertFilterRegexp: ^(Watchdog)$
```
as configuration option, the reboot is blocked, because the regexp is interpreted as `"^(Watchdog)$"` (yes, including the quotes).
```
time="2020-07-04T20:32:31Z" level=info msg="Kubernetes Reboot Daemon: 1.4.4"
time="2020-07-04T20:32:31Z" level=info msg="Node ID: xxx"
time="2020-07-04T20:32:31Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2020-07-04T20:32:31Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1m0s"
time="2020-07-04T20:32:31Z" level=info msg="Blocking Pod Selectors: []"
time="2020-07-04T20:32:31Z" level=info msg="Reboot on: SunMonTueWedThuFriSat …
```

Remove quote for parameter alert-filter-regexp

---

cmd/kured/Dockerfile

Without this patch, we need to build a cache and remove it
afterwards.  Since apk allows to work with no-cache and won't
leave artifacts, we should use it.
This will make the dockle best practices scanner happier.

fix: Follow DKL-DI-0004 guideline

---

.github/containerscan/allowedlist.yaml
.github/workflows/vulnerability-scan.yaml

Without this patch, there is no way we can see, in the development
process, if the image we are about to publish is insecure.
This is a problem as we might be releasing new versions of kured
with outdated base image which contains vulnerabilities.
This fixes it by creating a job which will show any eventual
vulnerability.

feat: Add security scanning into CI

---

Makefile

This automates the manifest and helm chart version handling.
Just pass the organisation and version in the make command to
update the manifests/helm charts.
This does not automate the helm chart version and does not
create a manifest used in the release process.

Release helper

---

cmd/kured/main.go

The default of 0 is taken as "delete immediately", which is not appropriate.
Fixes #236

Drain: allow pods grace period to terminate

---

README.md
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.yaml

The command-line option was changed in #213 and needed to be updated in the chart and docs.

rename annotation-ttl to lock-ttl in all places, follow-up to #213

---

.github/workflows/stale.yaml

Without this patch, we might hold old issues and PR for a long
time. Instead we should close them. People can reopen if necessary.
This would show that we have a proper triage process, and a proper
way to handle those.
Closes: #223

Auto expire issues and PRs

---

pkg/timewindow/timewindow.go
pkg/timewindow/timewindow_test.go

Time Wrap validation
As stated in the issue #204 it is not possible to time wrap rules. For that we need to add the logic that will adhere to those scenarios.
First we check for start and end time, if start is after end time, we need to validate if we want to wrap to the day before or to the day after.
For that we check the `loctime` value to see if it is before end time, we wrap with the day before, otherwise we wrap to the next day.
I added suggested test scenarios and others that check for a time wrap with not valid days.
fixes #204

Added support for time wrap in timewindow.Contains

---

DEVELOPMENT.md
README.md
charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.minikube.yaml
charts/kured/values.yaml
cmd/kured/main.go
kured-ds.yaml
pkg/notifications/slack/slack.go

Adds a way to tackle #125 by adding extra parameters `--slack-message-drain` and `--slack-message-reboot` which allow users to override the default slack messages `Draining node %s` and `Rebooting node %s`.
This is particularly helpful when using the current recommended way in slack to create webhooks (https://api.slack.com/messaging/webhooks) where the username and channel are both statically linked to the webhook URL. Using these parameters users can add extra information like the cluster name, region, and whatever else they need.
Sample using minikube for testing:

GH-125, add additional parameters for the drain/reboot slack message template

---

.github/kind-cluster.yaml
.github/workflows/smoke-tests.yml
tests/kind/create-reboot-sentinels.sh
tests/kind/follow-coordinated-reboot.sh

Without this patch, we don't test on release whether kured actually
works and behave well.
This is a problem, as a functional issue could have been hidden by
a recent change, as our testing is minimalist (only test the
usability, not the functionality).
Instead of testing manually, we should ensure this in CI.
This fixes it by adding a github action which tests the previously
built artifacts before publishing a release. The job consume the helm
chart in our code tree  (note: this relies on the last released image),
and run a functional test triggering a coordinated restart of a
whole 5 node cluster deployed with kind, through github actions.
Note: The github action needs to reset docker configuration, else
the reboot of the node (a docker container in kind) will fail.
It will be correctly …

Add smoke/basic functional test

---

tests/kind/follow-coordinated-reboot.sh

Without this, shellcheck will complain about double quotes
missing.

Fix shellcheck issue

---

tests/kind/follow-coordinated-reboot.sh

This will be necessary to find out why some docker containers fail
to come back up in github actions.

Add more logs into gates

---

.github/dependabot.yml

Without this patch, we'll get kubernetes updates.
This is not necessary, and could be even a problem on merge:
those kubernetes updates are done separately, knowingly,
to respect the life cycle of the kubernetes we need
(and stay one version below latest to have a larger coverage
of versions).
We could keep dependabot to update those on a lower frequency,
but that sounds clunky and not great. Instead disable them all,
and rely on the team to do this regular maintenance work.

Do not bump kubernetes with dependabot

---

.github/workflows/on-pr.yaml
.github/workflows/on-release.yaml
.github/workflows/on-tag.yaml
.github/workflows/periodics-daily.yaml

Without this, golang version used is the golang version decided
by github.
This is a problem, as it might shift over time, without our control.
This fixes it by getting the golang version from the go.mod.

Force golang version

---

.github/workflows/on-pr.yaml

Without this patch, the PR jobs are broken and no jobs are running.
This was a recently introduced typo in the last refactor of the
PR jobs.
This should fix it, and make the PR test working again.

Fix typo in github workflows

---

charts/kured/Chart.yaml
charts/kured/values.yaml

Without this patch, chart linting will fail: more than two
spaces are needed before a comment in the helm chart values.
This fixes it by adding one more space, and move the whole block
of comments for consistency.

Fix comment spacing

---

README.md

Corrected README `Setting a schedule` configuration example
Added = for the setting of the scheduling commands

Corrected README Setting a schedule configuration example

---

cmd/kured/Dockerfile

Until a new alpine image is created, we should ensure the latest
packages are used, and therefore we should upgrade default
installed packages.
Without this patch, we'll have outdated and vulnerable packages
until a new 3.12 image is released.
This is a problem, as we'll publish broken images.
This should temporarily workaround it, at the expense of larger
images (contains package cache)

Temporarily workaround alpine issue

---

.github/dependabot.yml

Without this patch, dependabot will still try to bump some k8s
dependencies.
This is a problem, as we need to bump them together, manually.
This should fix it by removing them all from dependabot.

Do not bump any k8s module

---

.github/workflows/on-master-push-charts.yaml
DEVELOPMENT.md

We are now testing the helm charts on each PR. They are now
ensured to be passing our tests and reviewed before merging.
This also means that the merged changes in the master branch
are reliable, and therefore can be consumed immediately.
Currently, we are waiting for a release to publish a helm
chart.
This is a problem as it means that the helm chart will
always lag behind, and we'll miss a few semantic versions,
if for example the helm chart is adapted multiple times
before the next release.
This should fix it by ensuring ALL the merged changes in
our helm chart will result in a new published helm chart.

Auto-publish helm chart on master change

---

.github/workflows/on-tag.yaml

Without this patch, the name of the image is not templated, which
cause the action to fail.
This should fix it, by ensuring the image scan action uses a
templated value, instead of incorrectly relying on shell templating,
which doesn't run in the action.

Fix automated tagging

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/templates/service.yaml
charts/kured/values.yaml

A small helm update to expose setting the service name for the service, and expose maxUnavailable when the the `updateStrategy` is set to `RollingUpdate`.

Expose the service name and maxUnavailable for rolling updates in helm chart

---

Makefile
charts/kured/Chart.yaml
charts/kured/README.md

Without this, it's possible that the helm chart documentation
contains the `image tag` version which might not be equal to
the version in the helm chart, as it's only an example.
This is a confusing, so instead we should use make to edit the
application version everywhere.
This fixes it by updating the Makefile to modify text of the
chart's README using a regex looking for something similar to
a version; then I used the updated makefile to edit the README.

Update helm chart README using Make

---

README.md
cmd/kured/main.go
pkg/taints/taints.go

This implements https://github.com/weaveworks/kured/issues/19
The idea is to set a prefer no schedule taint.
The taint is set when the reboot sentinel is found and removed after the restart.
In case the node can not restart immediately the taint asks the kubernetes scheduler to avoid placing new pods on the tainted node.
But this is only preferred, as a last resort the kubernetes scheduler does place pods onto the node.

implement issue-19 add prefer no schedule taint to avoid double draining of pods

---

cmd/kured/main.go

This PR changes the pre-reboot drain functionality so that it *always* runs, regardless of the value of the `Unschedulable` node property. Ostensibly this "skip if unschedulable" foo was added due to the fact that the value of `Unschedulable` will be set to false as a side-effect of a kured reboot operation, and if we're in a "retry" loop here, we shouldn't have to "drain again".
However, because kubectl drain is idempotent, we shouldn't have to worry about any of that: we can run it over and over again. And because this `drain` func actually does a cordon + drain (and it only performs the drain *if* a cordon is successful), we can be sure that we aren't going to be thrashing this node w/ respect to scheduled pods.
And in fact, the current implementation of "only drain if node is marked …

always drain before reboot

---

cmd/kured/main.go
kured-ds.yaml

This PR adds a new `--annotate-nodes` daemonset runtime argument, which does the following when enabled:
- adds a new node annotation `"weave.works/kured-most-recent-reboot-needed"` with a value of the current RFC3339 timestamp *as soon as kured identifies that a node needs to be rebooted*
- adds a new node annotation `"weave.works/kured-reboot-in-progress"` with a value of the current RFC3339 timestamp *as soon as kured identifies that a node needs to be rebooted*
The purpose of these node annotations is to allow other k8s node maintenance tooling to know about what kured is doing to these nodes. As a concrete example, this alpha project aims to take an OS disk image snapshot of a stable node in a cluster in order to update our "node pool recipe" to use it for future node scale out …

add node annotations to identify kured reboot operations

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.minikube.yaml
charts/kured/values.yaml

This PR follow up from the introduction of node annotations introduced in #296.
Here we enable that functionality in the standard helm chart via a `configuration.annotateNode` value property. By default the helm chart sets that value to false (in other words, it will not change any behaviors for folks using existing helm charts when they upgrade to this chart version).
Also bumps the chart version from 2.3.2 to 2.4.0

update chart definition to include --annotate-nodes

---

MAINTAINERS

Thanks a lot @ckotzbauer and @evrardjp for stepping up as maintainer and for your significant and sustained contributions to `kured`.
Thanks @hiddeco as well for stepping up as well.
I'm very pleased to see a small maintainers group coming together!

Adding a MAINTAINERS file

---

.github/workflows/on-pr.yaml
.github/workflows/periodics-daily.yaml

Without this patch, go test bugs can appear without getting caught.
This should fix it.

Add go tests for PRs

---

README.md
cmd/kured/main.go
go.mod
go.sum

Without this patch, kured can only notify via slack.
This patch gives the possibility to send notifications
across different technologies. Also, this patch makes
slack-hook-url, slack-username and slack-channel
deprecated (informed by a warning).
Also, updated the documentation (Readme).

Implement universal notification mechanism (NEW)

---

cmd/kured/main.go

Without this patch, the rebootCommand passed to invokeReboot is
ignored, and the command used for reboot is always systemctl reboot.
This is a problem, as we are aiming for flexible commands for this
release.
This fixes it by restoring the previous behaviour before commit
[1] happened.
[1]: https://github.com/weaveworks/kured/commit/694957d56e7729ba6493fadca6cd9c1ac0a398fa

Fix invoke reboot for custom commands

---

.github/workflows/on-pr-charts.yaml
.github/workflows/on-pr.yaml

Without this patch, github actions are lagging behind.
This should improve our coverage.

Update github actions

---

.github/ct.yaml

Without this patch, chart-testing is using the branch named
"master" by default.
This is a problem, as we just renamed our development branch
"main" instead of "master".
This should fix it by pointing to the right branch.

Add chart-testing target-branch

---

pkg/daemonsetlock/daemonsetlock.go

This PR replaces single DaemonSet GET calls to the k8s API with a go func-wrapped async + retry implementation.
Fixes #272
Originally implemented as PR #317, see that PR for historical review thread matter.

chore: retry daemonset get operations

---

.github/workflows/on-pr-charts.yaml

Without this change, the "Test helm chart (install) action" will
rightfully succeed when our helm chart gets installed and has
no syntax issues. However, it doesn't test if kured is properly
installed. For example, the helm chart can try to install a
yet unpublished image, and our test will succeed, as the syntax
is still valid.
This is a problem, as everything looks green, but it's not
effectively working. Our other jobs are focusing on code changes,
so it effectively overrides the image tag, which is not what
we want in this "Test helm chart" action.
This fixes it by adding an extra command in the test.

Reduce false positives

---

.github/workflows/on-pr.yaml
charts/kured/Chart.yaml
charts/kured/ci/prometheus-values.yaml
charts/kured/templates/service.yaml
charts/kured/values.yaml
tests/kind/test-metrics.sh

Without this, we can't know if the exposed prometheus metrics
behave properly.
This is a problem, as the only way we can evaluate the success
(right now), is a compilation success or failure from kured.
While this is a good start, it doesn't translate to what we
claim to offer: A boolean showing if a reboot is required.
This fixes it by creating a new github action workflow testing
if the float64 gauge is properly showing 0 for no reboot, 1 for reboot.
This is done by exposing the metrics endpoint through a node port.
A helm chart change was required to have the ability to expose
the service on a node port. We connect to the kind node through
docker in the `tests/test-metrics.sh`, where we curl the nodeport,
extract the only relevant metric, and compare it to the expected result.

Add prometheus export metrics functional testing

---

README.md
cmd/kured/main.go
kured-ds.yaml

This change supports throttling of reboots across the cluster by adding a new command line flag --lock-release-delay. When specified nodes will hold the lock for the provided amount of time after rebooting. That way pods can reschedule on the rebooted node and state can be replicated before the next node is rebooted.
Issue : #277

Add parameter for delaying release of lock

---

.github/workflows/on-pr-charts.yaml
.github/workflows/on-pr.yaml
.github/workflows/periodics-daily.yaml

We are relying on master, which might break anytime (or in this
case, moved to another branch).
Instead we should rely on a stable version, and unfreeze if
necessary. Dependabot helps us maintain those releases anyway.

Use stable kind-action

---

README.md
charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.minikube.yaml
charts/kured/values.yaml

Adds support for the --lock-release-delay parameter that was added in #352 to the helm chart. Setting `configuration.lockReleaseDelay=1h` for instance throttles node reboots to at most 1 per hour.
Issue: #277

Add lockReleaseDelay parameter to helm chart

---

.github/workflows/periodics-daily.yaml

our 'good first issue' issue label has no '-', add 'keep'

---

README.md

shoutrrr now have versioned docs to allow directly linking to the version that matches the one you use
changes should always backwards compatible, but not the other way around

link to versioned shoutrrr docs

---

charts/kured/Chart.yaml
charts/kured/values.yaml

This PR changes the default chart `rebootCommand` value to match the default in-code `--reboot-command` arg: "/bin/systemctl reboot".
Without this fix, Kured 1.7.0 is regressive for environments that don't have `/sbin/systemctl` present on their Linux distribution.
Original change was here:
https://github.com/weaveworks/kured/pull/394
Fixes #404

fix: common default reboot command for code and chart

---

README.md
cmd/kured/main.go
cmd/kured/main_test.go
kured-ds.yaml
pkg/alerts/prometheus.go
pkg/alerts/prometheus_test.go

This change allows the user to specify `--alert-firing-only=true` to change the Prometheus blocking checker to only consider firing alerts instead of also pending alerts, which can be a common and normal occurrence in clusters.
Fixes #393

Add --alert-firing-only parameter to only consider firing alerts

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/values.yaml

This change sets the default value for the DaemonSet updateStrategy to RollingUpdate to automatically update kured Pods on every change of the DaemonSet spec.
Fixes #413

Change helm chart default value for updateStrategy to RollingUpdate

---

cmd/kured/main.go

Currently, kured issues the system reboot command immediately after
kubectl drain finishes.
This is a problem for processes that need extra time to finish but aren't
running on pods and therefore aren't controlled by kubectl drain (e.g.
de-registering nodes from external load balancers).
This patch solves the problem by introducing a `reboot-delay` command
line argument that can be used to add a delay after kubectl drain
finishes but before the reboot command is issued.

Add `reboot-delay` command line argument

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.minikube.yaml
charts/kured/values.yaml
cmd/kured/main.go

Followup from https://github.com/weaveworks/kured/pull/341, exposes all of the new cli flags to the helm chart.

Add force-reboot and drain timeouts to chart config and ds

---

cmd/kured/main.go

This PR changes the drain Helper object we use for cordon/uncordon to include a bog standard background context object. We've observed in future versions of the kubectl API that a nil context object results in a runtime panic in the execution flow of a cordon/uncordon.
For example, in `v0.20.5` (the version of kubectl that kured currently uses) of the kubectl API the `RunCordonOrUncordon` function that kured depends upon uses the `PatchOrReplace` kubectl function under the hood:
https://github.com/kubernetes/kubectl/blob/v0.20.5/pkg/drain/default.go#L60
That's fine for now. But, in `v0.21.4` `RunCordonOrUncordon` (whose function interface is unchanged) uses `PatchOrReplaceWithContext` under the hood, and expects the passed-in `drain *Helper` to have a valid context child property to pass …

fix: don't use nil context in drain helper

---

.github/workflows/on-main-push.yaml
.github/workflows/on-tag.yaml
Makefile

This PR adds `quay.io` as second container-registry to our build-scripts.
The secret-variables for the quay.io credentials are WIP.
Maybe we should mention this change in the docs?

[WIP] Add quay.io as second registry

---

DEVELOPMENT.md

doc: some clarification of release-docs

---

cmd/kured/main.go
go.mod
go.sum

fixes #383
Environment Variables should be prefixed with `KURED_` and match the command flag names (`-` replaced with `_`)
if values are specified through both the command flag and environment variable, command flag takes precedence.

bind environment variables to cobra flags with viper

---

cmd/kured/main.go

Happy new year friends!!! 👏🏼 🍾 😄 
While testing out v1.9.0, I realized I made a mistake in https://github.com/weaveworks/kured/pull/464 PR that prints in the log the value of the Environment Variables that are being bound to command flags, since some of these are sensitive (like `KURED_NOTIFY_URL`) we don't want their values to end up in the logs.
This PR addresses it, I think this is relatively important to merge in and perhaps worth cutting a v1.9.1 since currently it leaks sensitive details to the logs.
apologies for not catching this sooner.
/cc @ckotzbauer @evrardjp @jackfrancis (just tagging you folks for awareness as you've had the chance to review the original PR)

don't print env variable values in the logs (some are sensitive)

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.yaml

Hi,
this PR adds the ability to define custom annotations for the kured daemonset through the `dsAnnotations` helm value.
Value name and template syntax have been chosen to be similar to the already existing `podAnnotations`.
This covers our kured use case where during kured first setup all reboots are temporarily suspended by locking the daemonset using the annotation on the daemonset (ref. https://github.com/weaveworks/kured#disabling-reboots).

Add ability to define ds annotations in helm chart

---

README.md

Add example for RHEL.
Fixes https://github.com/weaveworks/kured/issues/498

docs: add sentinel command example for RHEL family

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml

When running multiple clusters, user may want to route notifications to different Slack channels or use different Slack usernames when reporting Kured events from different clusters.
Allow for use of dynamic values with on-deployment templating by using `tpl` in Slack CLI parameters.

Helm chart: Use templating in Slack URL, channel and username

---

go.mod

Signed-off-by: Christian Kotzbauer <git@ckotzbauer.de>
To align with the upcoming update to `k8s.io/* 0.23.x`
Fix #511 
Ref #522 
Do we want to pin to specific versions to overcome #519?

Use go@1.17

---

cmd/kured/main.go

This PR adds retry logic to each cordon/uncordon/drain operation, to account for possible failures.
Here's a summary of these changes:
- If we're just instantiating and we already hold the lock (this is the scenario that happens when kured has just rebooted the node and the pod comes back online):
- if we fail to grab the k8s client for any reason, we will retry again in ~1 minute (continuously until we succeed)
- if we fail to uncordon the node, we will retry again in ~1 minute (continuously until we succeed)
- if we fail to delete any annotations, we will retry again in ~1 minute (continuously until we succeed)
The above essentially ensures that we don't leave a node in an "Unschedulable" state indefinitely. And more importantly, if there is some general cluster pathology that is …

retry cordon + drain if fail, keep lock

---

go.mod

Signed-off-by: Christian Kotzbauer <git@ckotzbauer.de>
Main is broken since the merge of go 1.17 yesterday.

fix: go mod tidy

---

charts/kured/Chart.yaml
charts/kured/README.md
charts/kured/templates/daemonset.yaml
charts/kured/values.yaml

This PR ensured that kured + k8s 1.24 is ready for changes to default control plane taint/toleration spec.
Rather than pass in the default tolerations via values.yaml, we use the built-in `.Capabilities` helm interface to determine at install time which tolerations to include by default.
If a user wishes to use configurable tolerations, this change respects that.
Fixes #538

helm: ensure kured on 1.24 gets the correct toleration

---

.github/workflows/on-main-push.yaml
.github/workflows/on-pr.yaml
.github/workflows/on-tag.yaml
.github/workflows/periodics-daily.yaml

This PR adds a ".x" range suffix to the `go-version` configuration of `actions/setup-go@v3` to ensure that we always run CI with the latest available patch release of go.
For reference:
https://github.com/npm/node-semver#x-ranges-12x-1x-12-
Fixes #519

ci: always use the latest golang patch version

---

README.md
cmd/kured/main.go

Add node labelling

---

charts/kured/Chart.yaml
charts/kured/templates/daemonset.yaml

This PR update daemonset tolerations so that both pre and 1.24+ taints are tolerated.
Fixes #556

tolerate both 1.24+ and prior control plane taints

---

README.md

This PR clarrifies how user can use --notify
-url flag and respect the username by adding
<username>@ in front of tokenA.
* Tested the syntax: slack://username@tokenA/tokenB/tokenC on a kind k8s cluster with kured as addon + a slack channel. 
```
command:
- /usr/bin/kured
- --notify-url=slack://kured-bot@<token>/<token>/<token>
- --period=20s
```
```
[kured-bot](https://app.slack.com/team/B01F49PD9EV)APP  
[3:23 PM](https://kured-tesing-personal.slack.com/archives/C01ERSH2PFD/p1653571403864349)
Draining node kind-worker2
[3:23](https://kured-tesing-personal.slack.com/archives/C01ERSH2PFD/p1653571404102789)
Rebooting node kind-worker2
```

improved documentation covering slack usage

---

README.md

since slack has implemented their new
way of authenticating apps, checked if
shoutrrr did cover that and tested the
implementation on a slack channel.
Tested on slack channel:
```
[kured-bot](https://app.slack.com/team/U03HGDTR8U9)APP  [1:21 PM](https://kured-tesing-personal.slack.com/archives/C01ERSH2PFD/p1653736871547619)
aaaa
```

updated slack-related documentation

---

README.md
cmd/kured/main.go

when reboot & uncordoning is successful -> notification will be sent.
Fixes: https://github.com/weaveworks/kured/issues/585
AFTER:
```
[kured-bot](https://app.slack.com/team)
APP  
[1:26 PM](https://kured-tesing-personal.slack.com/archives)
Draining node kind-worker2
[1:26](https://kured-tesing-personal.slack.com/archives)
Rebooting node kind-worker2
[1:27](https://kured-tesing-personal.slack.com/archives)
Node: kind-worker2 rebooted&uncordoned successfully!
```

added notification when uncordoning

---

.github/workflows/on-pr.yaml
.github/workflows/on-tag.yaml
.github/workflows/periodics-daily.yaml

This PR addresses the failing CI job `Azure/container-scan` which we use to validate the images we use in testing and building kured. This workaround follows the recommendation here:
https://github.com/Azure/container-scan/issues/146#issue-1293213052
Fixes #597

ci: address Azure/container-scan regression

---

README.md
cmd/kured/main.go

This PR updates the `README.md` command line flags content with the latest output from `go run cmd/kured/main.go --help`.
Issue #603 identified that the README was out of date.
Also sanitized the cobra command definitions a bit for better presentation, and incorporated some additional manual language that had been added to the `README.md`, but not the actual code.

update command line flags in README

---

MAINTAINERS

My maintainer email address is outdated, and is not
redirected anymore. This should fix it.
Signed-off-by: Jean-Philippe Evrard <open-source@a.spamming.party>

Update maintainer email address

---

README.md

To add clarity, we should publish, on our old page, the information about how to use the new helm charts.
Signed-off-by: Jean-Philippe Evrard <open-source@a.spamming.party>

Display new URL for redirected users

---

.github/workflows/on-main-push.yaml
.github/workflows/on-pr.yaml
.github/workflows/on-tag.yaml
.github/workflows/periodics-daily.yaml
DEVELOPMENT.md
Makefile
README.md
cmd/kured/main.go
cmd/kured/main_test.go
go.mod

Also drop Docker Hub as discussed.
Areas I did not touch:
- bot name, secrets
- image name
- LICENSE (would need to ask how/if that gets changed...?)
- anything in charts/ - will be handled by separate PR
- one mention in the Dev docs that we used to do some pre-release smoke-testing on the Weave Dev cluster

Change organisation to kubereboot, drop Docker Hub build

---

README.md

At some stage we changed to first Wednesday instead.

update meeting day

---

.github/workflows/on-pr.yaml
.github/workflows/periodics-daily.yaml
.lycheeignore
README.md

Move to lychee action as well.
Fixes: #308

Use lychee link checker and add Fossa badge

---

DEVELOPMENT.md

The branch where k8s 1.10 support was developped is not listed in github. It makes the link in DEVELOPMENT reaching a 404. Let us point to the merged SHAs of the changes instead.
Signed-off-by: Jean-Philippe Evrard <open-source@a.spamming.party>

Remove deadlink to k8s 1.10 support branch

---

.github/workflows/on-main-push.yaml
.github/workflows/on-pr.yaml
.github/workflows/on-tag.yaml
.github/workflows/periodics-daily.yaml

Fixes: #685
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Replace set-output with GITHUB_OUTPUT

---

.github/workflows/on-tag.yaml

A mistake on my part.
The complete diff, together with #686 is now:
```diff
diff --git a/.github/workflows/on-main-push.yaml b/.github/workflows/on-main-push.yaml
index 09c2197..343f780 100644
--- a/.github/workflows/on-main-push.yaml
+++ b/.github/workflows/on-main-push.yaml
@@ -47,7 +47,7 @@ jobs:
uses: docker/setup-buildx-action@v2
- name: Find current tag version
-        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
+        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
id: tags
- name: Setup GoReleaser
diff --git a/.github/workflows/on-pr.yaml b/.github/workflows/on-pr.yaml
index 71ea50c..bd53f21 100644
--- a/.github/workflows/on-pr.yaml
+++ b/.github/workflows/on-pr.yaml
@@ -83,7 …
```

brown paper bag for #686

---

go.mod

drop unnecessary replacement for go-restful CVE

---

cmd/kured/main.go

This PR moves the checking of "reboot blockers" (e.g., matching podSelectors running on the node to-be-rebooted) further down in the conditional reboot flow so that those checks happen _after_ we (conditionally) annotate the nodes.
This enables the following when a reboot is detected (by default the presence of the `/var/run/reboot-required` file):
1. If `--annotate-nodes` is true, we annotate the nodes with the following annotations:
- `"weave.works/kured-reboot-in-progress"` (indicates that this node will be rebooted at some point in the near future)
- `"weave.works/kured-most-recent-reboot-needed"` (marks a timestamp of when this need for reboot was detected by kured)
2. After we annotate nodes, add a "prefer no schedule taint" to communicate a preference (though not a strict …

fix: annotate nodes for reboot before aborting due to blocked

---

cmd/kured/main.go

This PR is related to issue #737. While it does not add support for custom drain commands, it adds support for configuring the pod-selector to be used for draining, which should be sufficient to address all the Longhorn related issues.

Support pod-selector for drain command

---

cmd/kured/main.go

fix: log on unusual sentinel-command exit code

---

cmd/kured/main.go
kured-ds.yaml

Kured runs with `hostNetwork=true`, which means that, today, Kured will expose the metrics endpoint on what is probably a public interface for many deployments. The metrics are generally not sensitive data, but as a policy it seems wrong to do this. Allowing the user to configure which port Kured exposes metrics on is a step in the right direction, but the current implementation does not allow the user to specify the address to listen on. For example, in our use case, we would like for the metrics server to _only_ listen on a loopback address. This would allow us to put [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) in front of the metrics endpoint.
This change could slightly complicate the Helm chart because it not only affects the metrics endpoint, but also the …

Adds new flag --metrics-host

---

.github/workflows/on-pr.yaml
cmd/kured/main.go
kured-ds.yaml
pkg/daemonsetlock/daemonsetlock.go
pkg/daemonsetlock/daemonsetlock_test.go
tests/kind/follow-coordinated-reboot.sh

Currently in kured a single node can get a lock with Acquire. There could be situations where multiple nodes might want a lock in the event that a cluster can handle multiple nodes being rebooted. This adds the side-by-side implementation for a multiple node lock situation.
Added unit tests. Also ran a manual test with `--concurrency=2`. I observed that two nodes rebooted at the same time:
```
$ kubectl get no
NAME                                STATUS                        ROLES   AGE   VERSION
aks-nodepool1-14327021-vmss000000   Ready                         agent   24m   v1.23.8
aks-nodepool1-14327021-vmss000001   Ready                         agent   24m   v1.23.8
aks-nodepool1-14327021-vmss000002   Ready                         agent   24m   v1.23.8
aks-nodepool1-14327021-vmss000003 …
```

Add multiple concurrent node reboot feature

---

cmd/kured/main.go
kured-ds.yaml
pkg/alerts/prometheus.go
pkg/alerts/prometheus_test.go

Adding "--alert-filter-match-only" argument which inverts the behavior of "alert-filter-regexp". When alert-filter-match-only=true, kured will block on any active alerts that match the regexp defined in 'alert-filter-regexp'
A use case for this is: 
Fire alerts if the cluster is becoming unhealthy (a % of nodes are no longer == Ready). Immediately prevent kured from continuing to drain and reboot.

add argument to invert the behavior of alert-filter-regexp

---

cmd/kured/main.go

Fixes #792
This PR moves the "is this node blocked for reboot?" foo earlier in the code flow in the main "does node need to be rebooted?" loop. The purpose is to determine whether or not the node is blocked for reboot prior to trying to acquire a node lock that will prevent another node in the cluster from being rebooted.
The purpose of blocking a node from rebooting is to implement node-specific safety checks prior to taking a node offline (an obvious side-effect of a reboot). These safety checks should be independent from the configuration that enforces how many nodes may go offline at any time (implemented via the node reboot concurrency config + the daemonset lock). This is what informs my thinking that we should simply check for a blocking condition prior to attempting to acquire a …

fix: don’t hold node lock if reboot is blocked

---

kured-ds.yaml

- Support pod-selector for drain command (#788)
- Use readOnlyRootFilesystem (#805)
- Log on unusual sentinel-command exit code (#806)
- Don’t hold node lock if reboot is blocked (#819)
- Add argument to invert the behavior of alert-filter-regexp (#786)
- Add multiple concurrent node reboot (#660)
- Adds new flag --metrics-host (#811)
- Use go@1.20, k8s@0.27.4, test k8s 1.26-1.28 (#818)
- updated build-tools (#809)
- confirm cosign prompt
- Update alpine to 3.18.3 (#815)
The daemon image contains a 1.27.x k8s.io/{client-go,kubectl} for the purposes of maintaining the lock and draining worker nodes. Kubernetes aims to provide forwards & backwards compatibility of one minor version between client and server, so this should work on 1.26.x, 1.27.x and 1.28.x
Thanks a lot to everyone who …

Release 1.14.0

---

.github/scripts/goreleaser-install.sh

Replace aarch64, ppc64le arm armv7l with matching architectures for the goreleaser.
Proposed solution for https://github.com/kubereboot/kured/issues/823

Fix the goreleaser architecture for arm and ppc

---

cmd/kured/main.go
kured-ds.yaml

This PR adds a `--drain-delay` flag.
The duration given will delay the node draining process to allow for other controllers in the cluster to complete work.
We are using `--pre-reboot-node-labels=node.kubernetes.io/exclude-from-external-load-balancers=true` to signal the load balancer controller to start draining connections from the node as it is about to be drained.
With the flag added we can delay the draining process to ensure the load balancer controller has enough time to remove the node from active traffic flow before the draining starts.

feat: add drain delay

---

.github/workflows/on-pr.yaml
Makefile
cmd/kured/main.go
kured-ds-signal.yaml
kured-ds.yaml
pkg/reboot/command.go
pkg/reboot/reboot.go
pkg/reboot/signal.go
pkg/util/util.go

Based on #813
close #416 
close #722
This PR adds a `--reboot-method` flag with "command" (default) and "signal" option. The "command" option uses the `--reboot-command` on the host with `nsenter` as before. The new "signal" mode uses a `SIGRTMIN+5` signal by default against PID 1 (systemd) to reboot the node. The signal can be changed via `--reboot-signal` flag.
With this, the kured pod runs without privileged mode.
This PR is published as docker-image (amd64 and arm64): `ghcr.io/ckotzbauer/kured:1.14.0-alpha.2`
Usage (based on the latest helm-chart) - Helm values.yaml:
```yaml
image:
repository: ghcr.io/ckotzbauer/kured
tag: 1.14.0-alpha.2
updateStrategy: RollingUpdate
configuration:
period: "0h0m30s"
rebootDelay: 0h1m0s
rebootSentinel: /sentinel/reboot-required
extraArgs: …
```

Add signal-reboot

---

go.mod

This PR updates the version of go used to build the project to 1.22.

update go to 1.22

---

CONTRIBUTING.md

Without this patch, the copy of the contributing.md into our doc site (generated from [1] and [2]) will refer to a local README.md into the website git repo, which is not existing.
This is a problem, as it generates dead link for lychee on local runs in 'content/en/docs/development.md'.
This fixes it by making the link absolute, while keeping the CONTRIBUTING.md in sync between repos. The alternative would be to edit the site generator in [1]. Yet, I believe having an absolute link does not hurt, because we already use the full git repo in other parts of the same documentation.
[1]: https://github.com/kubereboot/website/blob/5da8aba559460ef7a8c363ab021328cba9e0deda/hack/gen-content.py
[2]: https://github.com/kubereboot/website/blob/5da8aba559460ef7a8c363ab021328cba9e0deda/external-sources/ …

Change relative link to absolute link

---

Dockerfile

Without this, docker buildx will complain about the
following issues:
- "RedundantTargetPlatform: Setting platform to predefined $TARGETPLATFORM in
FROM is redundant as this is the default behavior"
- "FromAsCasing: 'as' and 'FROM' keywords' casing do not match"
This fixes it.

Cleanup dockerfile

---

.trivyignore

Now that we are building with latest 1.22, the exception should not be used anymore.

Remove security exception

---

Makefile

kured linking needs the goreleaser command line, yet it does not ensure it is present.
This fixes it by ensuring the bootstrap-tools are always fetched first.

bootstrap-tools are required for kured bin

---

.github/workflows/on-pr.yaml
Makefile
cmd/kured/main.go
pkg/daemonsetlock/daemonsetlock.go
pkg/timewindow/days.go
pkg/timewindow/timewindow.go
tests/kind/main_test.go
tests/kind/testfiles/podblocker.sh

- **Add e2e test concurrency w/ signal**
- **Add podblocker test**
- **Rename "version" with "variant" in tests**
- **Fix Staticcheck's SA1024 (subset with dupe chars)**
- **Fix Staticcheck's ST1005**
- **Fix incorrect string prints**
- **Add staticcheck in make tests**

improve tests

---

.github/workflows/on-pr-docs.yaml
.github/workflows/on-pr.yaml

This PR moves the verify docs link into its own PR trigger config so that it only runs if markdown files are updated.
We already have a periodic job validating links, so if there are not PRs for a period of time we'll still be alerted when links break.

Validate external links for md updates only on PR

---

.golangci.yml
CONTRIBUTING.md
Makefile
cmd/kured/main.go
internal/validators.go
pkg/blockers/blockers.go
pkg/blockers/kubernetespod.go
pkg/blockers/prometheus.go
pkg/checkers/checker.go
pkg/daemonsetlock/daemonsetlock.go
pkg/delaytick/delaytick.go
pkg/reboot/command.go
pkg/reboot/reboot.go
pkg/taints/taints.go
pkg/timewindow/days.go
pkg/timewindow/timewindow.go

This PR addresses issue #1135.
- Adds a `golangci-lint` configuration file (`.golangci.yml`) to standardize linting rules.  
- Updates the Makefile to install and run `golangci-lint` via `make lint`.

add golangci lint

---

CONTRIBUTING.md

Contributing still mentions the dockerhub file instead of the combined file.
This fixes it.

Fix inconsistent contributing guide
